# -*- mode: python ; coding: utf-8 -*-

import os
import sys
from pathlib import Path

block_cipher = None
datas = [
    ('static', 'static'),
]

if os.path.exists('bootstrap_secret.txt'):
    datas.append(('bootstrap_secret.txt', '.'))

a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=[
        'standard_auto_downloader_core',
        'flask',
        'waitress',
        'pdfplumber',
        'pdfminer',
        'PIL',
        'selenium',
        'selenium.webdriver',
        'selenium.webdriver.chrome',
        'selenium.webdriver.chrome.webdriver',
        'selenium.webdriver.chrome.service',
        'selenium.webdriver.chrome.options',
        'selenium.webdriver.chromium',
        'selenium.webdriver.chromium.webdriver',
        'selenium.webdriver.chromium.service',
        'selenium.webdriver.chromium.options',
        'selenium.webdriver.common.by',
        'selenium.webdriver.common.keys',
        'selenium.webdriver.common.action_chains',
        'selenium.webdriver.common.alert',
        'selenium.webdriver.support.ui',
        'selenium.webdriver.support.expected_conditions',
        'selenium.webdriver.remote',
        'selenium.webdriver.remote.webdriver',
        'selenium.webdriver.remote.webelement',
        'selenium.webdriver.remote.command',
        'selenium.webdriver.remote.remote_connection',
        'selenium.webdriver.remote.errorhandler',
        'bs4',
        'lxml',
        'lxml.etree',
        'lxml._elementpath',
        'asyncio',
        'dataclasses',
        'pathlib',
        'urllib.parse',
        'urllib.request',
        'json',
        're',
        'time',
        'logging',
        'datetime',
        'typing',
        'traceback',
        'hashlib',
        'base64',
        'tempfile',
        'shutil',
        'fitz',
        'docx',
        'docx.opc',
        'docx.opc.constants',
        'docx.opc.package',
        'docx.opc.part',
        'docx.oxml',
        'docx.oxml.ns',
        'docx.oxml.xmlchemy',
        'docx.shared',
        'docx.text',
        'docx.text.paragraph',
        'docx.text.run',
        'docx.table',
        'openpyxl',
        'openpyxl.cell',
        'openpyxl.worksheet',
        'openpyxl.workbook',
        'xlrd',
        'rapidocr_onnxruntime',
        'requests',
        'csv',
        'zipfile',
        'io',
        'platform',
        'socket',
        'uuid',
        'ssl',
        'cryptography',
        'cryptography.hazmat.primitives.ciphers.aead',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'sklearn',
        'tensorflow',
        'torch',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
        'playwright',
        'playwright.async_api',
        'playwright.sync_api',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='LabClient',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,  # 显示控制台窗口，便于调试
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico' if os.path.exists('icon.ico') else None,  # 如果有图标
)
